common/models/Apk.php
<?php

namespace common\models;

use Yii;
use yii\helpers\Html;

/**
 * This is the model class for table "apk".
 *
 * @property int $id
 * @property string $title
 * @property string $content
 * @property string $tags
 * @property int $status
 * @property int $create_time
 * @property int $update_time
 * @property int $author_id
 *
 * @property Adminuser $author
 * @property Apkstatus $status0
 */
class Apk extends \yii\db\ActiveRecord
{
    private $_oldTags;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'apk';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'content', 'status', 'author_id'], 'required'],
            [['content', 'tags'], 'string'],
            [['status', 'create_time', 'update_time', 'author_id'], 'integer'],
            [['title'], 'string', 'max' => 128],
            [['author_id'], 'exist', 'skipOnError' => true, 'targetClass' => Adminuser::className(), 'targetAttribute' => ['author_id' => 'id']],
            [['status'], 'exist', 'skipOnError' => true, 'targetClass' => Apkstatus::className(), 'targetAttribute' => ['status' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => '标题',
            'content' => '内容',
            'tags' => '标签',
            'status' => '状态',
            'create_time' => '创建时间',
            'update_time' => '更新时间',
            'author_id' => '作者姓名',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthor()
    {
        return $this->hasOne(Adminuser::className(), ['id' => 'author_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStatus0()
    {
        return $this->hasOne(Apkstatus::className(), ['id' => 'status']);
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert))
        {
            if ($insert) {
                $this->create_time = time();
                $this->update_time = time();
            }
            else
            {
                $this->update_time = time();
            }
            return true;
        }
        else
        {
            return false;
        }
    }

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        $this->_oldTags = $this->tags;
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        Tag::updateFrequency($this->_oldTags, $this->tags);
    }

    public function afterDelete()
    {
        parent::afterDelete(); // TODO: Change the autogenerated stub
        Tag::updateFrequency($this->tags, '');
    }

    public function getUrl()
    {
        return Yii::$app->urlManager->createUrl(
            ['apk/detail','id'=>$this->id,'title'=>$this->title]);
    }

    public function getBeginning($length=288)
    {
        $tmpStr = strip_tags($this->content);
        $tmpLen = mb_strlen($tmpStr);

        $tmpStr = mb_substr($tmpStr,0,$length,'utf-8');
        return $tmpStr.($tmpLen>$length?'...':'');
    }

    public function getTagLinks()
    {
        $links=array();
        foreach(Tag::string2array($this->tags) as $tag)
        {
            $links[]=Html::a(Html::encode($tag),array('apk/index','ApkFrontSearch[tags]'=>$tag));
        }
        return $links;
    }

    public function getTimeliCount()
    {
        return Timeli::find()->where(['apk_id'=>$this->id,'status'=>2])->count();
    }

    public function getActiveTimelis()
    {
        return $this->hasMany(Timeli::className(), ['apk_id' => 'id'])
            ->where('status=:status',[':status'=>2])->orderBy('id DESC');
    }

    /*
    public function fields()
    {
        return [
            'id',
            'title',
            '内容' => 'content',
            'status' => function ($model) {
                return $model->status == self::STATUS_DRAFT ? '草稿' : '已发布';
            },
            'createdBy' => function ($model) {
                return $model->createdBy->realname;
            },
        ];

                    public function extraFields()
                    {
                        return ['createdBy'];
                    }


//        $fields = parent::fields();
//
//        unset($fields['updated_at']);
//
//        return $fields;

    }  */


}

common/models/Timeli.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "timeli".
 *
 * @property int $id
 * @property string $content
 * @property int $status
 * @property int $create_time
 * @property int $userid
 * @property string $email
 * @property string $url
 * @property int $apk_id
 * @property int $remind 0:未提醒 1:已提醒
 */
class Timeli extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'timeli';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['content', 'status', 'userid', 'email', 'apk_id'], 'required'],
            [['content'], 'string'],
            [['status', 'create_time', 'userid', 'apk_id', 'remind'], 'integer'],
            [['email', 'url'], 'string', 'max' => 128],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'content' => '内容',
            'status' => '状态',
            'create_time' => '创建时间',
            'userid' => '用户',
            'email' => 'Email',
            'url' => 'Url',
            'apk_id' => 'Apk ID',
            'remind' => '是否提醒',
        ];
    }

    /////////////////////---------------下面三个方法没有自动生成（手动补上去的），估计没有做好表之间的关联吧。---------

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getApk()
    {
        return $this->hasOne(Apk::className(), ['id' => 'apk_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStatus0()
    {
        return $this->hasOne(Timelistatus::className(), ['id' => 'status']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'userid']);
    }

    public function getBeginning()
    {
        $tmpStr=strip_tags($this->content);
        $tmpLen=mb_strlen($tmpStr);

        return mb_substr($tmpStr,0,20,'utf-8').(($tmpLen>20)?'...':'');
    }

    public function approve()
    {
        $this->status=2;
        return ($this->save()?true:false);
    }

    public static function getPengdingTimeliCount()
    {
        return Timeli::find()->where(['status'=>1])->count();
    }

    public static function findRecentTimelis($limit=10)
    {
        return Timeli::find()->where(['status'=>2])->orderBy('create_time DESC')
            ->limit($limit)->all();
    }
}

backend/controllers/ApkController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Apk;
use common\models\ApkSearch;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ApkController implements the CRUD actions for Apk model.
 */
class ApkController extends ACFController
{
    /**
     * {@inheritdoc}
     */
//    public function behaviors()
//    {
//        return [
//            'verbs' => [
//                'class' => VerbFilter::className(),
//                'actions' => [
//                    'delete' => ['POST'],
//                ],
//            ],
//        ];
//    }

    /**
     * Lists all Apk models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ApkSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Apk model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        // test code
//        $tmp = Apk::find()->where(['id'=>32])->one();
//        $tmp = Apk::findOne(32);
//        $tmp = Apk::find()->where(['status'=>2])->all();
//        $tmp = Apk::findAll(['status'=>2]);
//        $tmp = Apk::find()->where(['AND', ['status' => 2], ['id' => 32], ['LIKE', 'title', 'cloud']])->orderBy('id')->all();
//        var_dump($tmp);
//        foreach ($tmp as $item) {
//            echo $item->title;
//        }
//        exit(0);
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Apk model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if  (!Yii::$app->user->can('createApk')) {
            throw new ForbiddenHttpException('对不起，您没有新增应用权限！');
        }
        $model = new Apk();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Apk model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        if  (!Yii::$app->user->can('updateApk')) {
            throw new ForbiddenHttpException('对不起，您没有修改应用权限！');
        }
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Apk model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        if  (!Yii::$app->user->can('deleteApk')) {
            throw new ForbiddenHttpException('对不起，您没有删除应用权限！');
        }
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Apk model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Apk the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Apk::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }


}

frontend/controllers/ApkController.php
<?php

namespace frontend\controllers;

use common\models\LoginForm;
use common\models\Tag;
use common\models\Timeli;
use common\models\User;
use frontend\models\ApkFrontSearch;
use Yii;
use common\models\Apk;
use common\models\ApkSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ApkController implements the CRUD actions for Apk model.
 */
class ApkController extends Controller
{
    public $added=0; //0代表还没有新Timeli
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            //页面缓存使用的同时还可以使用片段缓存、数据缓存以及renderDynamic动态数据
            'pageCache'=>[
                'class'=>'yii\filters\PageCache',
                'only'=>['index'],
                'duration'=>600,
                'variations'=>[//可以根据下面两个参数设置不同缓存,page和ApkFrontSearch所处位置在url中，他们两个是引起变化的因素
                    Yii::$app->request->get('page'),
                    Yii::$app->request->get('ApkFrontSearch'),
                ],
                'dependency'=>[
                    'class'=>'yii\caching\DbDependency',
                    'sql'=>'select count(id) from apk',
                ],
            ],
            'httpCache'=>[
                'class'=>'yii\filters\HttpCache',
                'only'=>['detail'],
                'lastModified'=>function ($action,$params){
                    $q = new \yii\db\Query();
                    return $q->from('apk')->max('update_time');//根据apk的最后修改时间来做http缓存的Last Modified，可以在chrome开发者工具中查看
                },
                'etagSeed'=>function ($action,$params) {
                    $post = $this->findModel(Yii::$app->request->get('id'));
                    return serialize([$post->title,$post->content]);//可以在chrome开发者工具中查看etag
                },

                'cacheControlHeader' => 'public,max-age=600',//可以在chrome开发者工具中查看Cache Control

            ],
        ];
    }

    /**
     * Lists all Apk models.
     * @return mixed
     */
    public function actionIndex()
    {
        $tags = Tag::findTagWeights();
        $recentTimelis = Timeli::findRecentTimelis();
        //注意，如果其他地方都用ApkFrontSearch，这里传递到页面的也要用ApkFrontSearch
        $searchModel = new ApkFrontSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'tags' => $tags,
            'recentTimelis' => $recentTimelis,
        ]);
    }

    /**
     * Displays a single Apk model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Apk model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Apk();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Apk model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Apk model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Apk model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Apk the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Apk::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionDetail($id)
    {
        //step1
        $model = $this->findModel($id);
        $tags = Tag::findTagWeights();
        $recentTimelis = Timeli::findRecentTimelis();

        $userMe = User::findOne(Yii::$app->user->id);

        if (!$userMe) {
            return $this->redirect(['site/login',
                'model' => new LoginForm(),//去登录吧
            ]);
        }

        $timeliModel = new Timeli();
        $timeliModel->email = $userMe->email;
        $timeliModel->userid = $userMe->id;

        //step2
        if($timeliModel->load(Yii::$app->request->post()))
        {
            $timeliModel->status = 1; //新评论默认状态为 pending
            $timeliModel->apk_id = $id;
            if($timeliModel->save())
            {
                $this->added=1;
            }
        }

        //step3.传数据给视图渲染

        return $this->render('detail',[
            'model'=>$model,
            'tags'=>$tags,
            'recentTimelis'=>$recentTimelis,
            'timeliModel'=>$timeliModel,
            'added'=>$this->added,
        ]);
    }
}

frontend/views/apk/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Apk */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="apk-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'content')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'tags')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'status')->textInput() ?>

    <?= $form->field($model, 'create_time')->textInput() ?>

    <?= $form->field($model, 'update_time')->textInput() ?>

    <?= $form->field($model, 'author_id')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/apk/_guestform.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\timeli */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="timeli-form">

    <?php $form = ActiveForm::begin([
        'action'=>['apk/detail','id'=>$id,'#'=>'timelis'],
        'method'=>'post',
    ]); ?>


    <div class="row">
        <div class="col-md-12"><?= $form->field($timeliModel,'content')->textarea(['row'=>6])?></div>
    </div>

    <div class="form-group">
        <?= Html::submitButton('发表版本记录', ['class' =>'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/apk/_listitem.php
<?php
use yii\helpers\Html;
?>

<div class="post">
    <div class="title">
        <h2><a href="<?= $model->url;?>"><?= Html::encode($model->title);?></a></h2>

        <div class="author">
            <span class="glyphicon glyphicon-time" aria-hidden="true"></span><em><?= date('Y-m-d H:i:s',$model->create_time)."&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";?></em>
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span><em><?= Html::encode($model->author->nickname);?></em>
        </div>
    </div>

    <br>
    <div class="content">
        <?= $model->beginning;?>
    </div>

    <br>
    <div class="nav">
        <span class="glyphicon glyphicon-tag" aria-hidden="true"></span>
        <?= implode(', ',$model->tagLinks);?>
        <br>
        <?= Html::a("版本 ({$model->timeliCount})",$model->url.'#timelis')?> | 最后修改于 <?= date('Y-m-s H:i:s',$model->update_time);?>
    </div>

</div>

frontend/views/apk/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\ApkSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="apk-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'content') ?>

    <?= $form->field($model, 'tags') ?>

    <?= $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'create_time') ?>

    <?php // echo $form->field($model, 'update_time') ?>

    <?php // echo $form->field($model, 'author_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/apk/_timeli.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>

<?php foreach($timelis as $timeli): ?>

    <div class="timeli">

        <div class="row">
            <div class="col-md-12">
                <div class="timeli_detail">
                    <p class="bg-info">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                        <em><?= Html::encode($timeli->user->username);?>;</em>
                        <br>
                        <?= nl2br($timeli->content);?>
                        <br>
                        <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
                        <em><?= date('Y-m-d H:i:s',$timeli->create_time);?>;</em>
                    </p>
                </div>
            </div>
        </div>
    </div>

<?php endforeach;?>

frontend/views/apk/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Apk */

$this->title = 'Create Apk';
$this->params['breadcrumbs'][] = ['label' => 'Apks', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="apk-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/apk/detail.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\ListView;
use frontend\components\TagsCloudWidget;
use frontend\components\RctReplyWidget;

use yii\helpers\HtmlPurifier;
use common\models\Timeli;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel common\models\PostSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

?>

<div class="container">

    <div class="row">

        <div class="col-md-9">

            <ol class="breadcrumb">
                <li><a href="<?= Yii::$app->homeUrl;?>">首页</a></li>
<!--                <li><a href="<?//= Yii::$app->urlManager->createUrl(['apk/index']);?>">应用列表</a></li>-->
                <li><a href="<?= Url::to(['apk/index']);?>">应用列表</a></li>
                <li class="active"><?= $model->title?></li>
            </ol>

            <div class="post">
                <div class="title">
                    <h2><a href="<?= $model->url;?>"><?= Html::encode($model->title);?></a></h2>
                    <div class="author">
                        <span class="glyphicon glyphicon-time" aria-hidden="true"></span><em><?= date('Y-m-d H:i:s',$model->create_time)."&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";?></em>
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span><em><?= Html::encode($model->author->nickname);?></em>
                    </div>
                </div>


                <br>

                <div class="content">
                    <?= HTMLPurifier::process($model->content)?>
                </div>

                <br>

                <div class="nav">
                    <span class="glyphicon glyphicon-tag" aria-hidden="true"></span>
                    <?= implode(', ',$model->tagLinks);?>
                    <br>
                    <?= Html::a("版本记录({$model->TimeliCount})",$model->url.'#Timelis');?>
                    最后修改于<?= date('Y-m-d H:i:s',$model->update_time);?>
                </div>
            </div>

            <div id="Timelis">

                <?php if($added) {?>
                    <br>
                    <div class="alert alert-warning alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>

                        <h4>谢谢您的回复，我们会尽快审核后发布出来！</h4>

                        <p><?= nl2br($timeliModel->content);?></p>
                        <span class="glyphicon glyphicon-time" aria-hidden="true"></span><em><?= date('Y-m-d H:i:s',$model->create_time)."&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";?></em>
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span><em><?= Html::encode($model->author->nickname);?></em>
                    </div>
                <?php }?>

                <?php if($model->timeliCount>=1) :?>

                    <h5><?= $model->timeliCount.'条版本记录';?></h5>
                    <?= $this->render('_timeli',array(
                        'apk'=>$model,
                        'timelis'=>$model->activeTimelis,
                    ));?>
                <?php endif;?>

                <h5>发表版本记录</h5>
                <?php
                $timeliModel =new Timeli();
                echo $this->render('_guestform',array(
                    'id'=>$model->id,
                    'timeliModel'=>$timeliModel,
                ));?>

            </div>

        </div>


        <div class="col-md-3">
            <div class="searchbox">
                <ul class="list-group">
                    <li class="list-group-item">
                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span> 查找应用
                    </li>
                    <li class="list-group-item">
                        <form class="form-inline" action="index.php?r=post/index" id="w0" method="get">
                            <div class="form-group">
                                <input type="text" class="form-control" name="PostSearch[title]" id="w0input" placeholder="按标题">
                            </div>
                            <button type="submit" class="btn btn-default">搜索</button>
                        </form>

                    </li>
                </ul>
            </div>

            <div class="tagcloudbox">
                <ul class="list-group">
                    <li class="list-group-item">
                        <span class="glyphicon glyphicon-tags" aria-hidden="true"></span> 标签云
                    </li>
                    <li class="list-group-item">
                        <?= TagsCloudWidget::widget(['tags'=>$tags])?>
                    </li>
                </ul>
            </div>


            <div class="Timelibox">
                <ul class="list-group">
                    <li class="list-group-item">
                        <span class="glyphicon glyphicon-Timeli" aria-hidden="true"></span> 最新回复
                    </li>
                    <li class="list-group-item">
                        <?= RctReplyWidget::widget(['recentTimelis'=>$recentTimelis])?>
                    </li>
                </ul>
            </div>


        </div>


    </div>

</div>

frontend/views/apk/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Apk */

$this->title = 'Update Apk: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Apks', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="apk-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/apk/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Apk */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Apks', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="apk-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'title',
            'content:ntext',
            'tags:ntext',
            'status',
            'create_time:datetime',
            'update_time:datetime',
            'author_id',
        ],
    ]) ?>

</div>